BASE_URL = 'https://www.dlm1947.com'
DEFAULT_SEARCH_KEYWORD = '6i7'
DEFAULT_START_PAGE = 1
DEFAULT_END_PAGE = 5

KEY_TITLE = 'title'
KEY_LINK = 'link'
KEY_PRODUCT_NAME = 'product_name'
KEY_PRODUCT_NUM = 'product_num'
KEY_REGULAR_PRICE = 'regular_price'
KEY_SALE_PRICE = 'sale_price'
KEY_IMAGE_LINK = 'image'
KEY_COLORS = 'color'
KEY_DETAIL_IMAGES_LINK = 'detail_image'

KEY_MAN_TOP_SIZE = 1
KEY_MAN_BOTTOM_SIZE = 2
KEY_WOMAN_TOP_SIZE = 3
KEY_WOMAN_BOTTOM_SIZE = 4
KEY_HAT_SIZE = 5
KEY_ETC_SIZE = 6

SIZE_DATA_SET = {
    KEY_MAN_TOP_SIZE: "95,100,105,110",
    KEY_MAN_BOTTOM_SIZE: "78,80,82,84,86,88,92,96",
    KEY_WOMAN_TOP_SIZE: "90,95,100,105",
    KEY_WOMAN_BOTTOM_SIZE: "64,67,70,73,76,79,82",
    KEY_HAT_SIZE: "057",
    KEY_ETC_SIZE: "000"
}